# Generated by Django 4.0.4 on 2022-05-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_reservation_rental_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='rental_id',
            new_name='rental',
        ),
    ]
